spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: wikimedia_consumer_1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  datasource:
    url: jdbc:mysql://localhost:3306/wikimedia
    username: user1
    password: Mysql@123

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
        jdbc:
          batch_size: 50
        order_updates: true
        order_inserts: true
    hibernate:
      ddl-auto: update